name: Deploy Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Test
        run: npm test

      - name: Package website
        run: |
          mkdir package
          cp index.html style.css script.js package/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::615693092027:role/github-actions-devops-deploy
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./package s3://devops-cicd-website-vineet-2026 --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3AH1SXATC3SOL \
            --paths "/*"